### ISSUE TITLE
junos_get_config doesn't work when using multiple entries in the filter

### ISSUE THREAD

**Issue by jedelman8** [Juniper/ansible-junos-stdlib#145]
When filter is a single element, it works fine.  When I use `filter='interfaces/protocols'`  it no longer works.  Knowing this used to work, I just rolled back to the version before the last commit on this file as shown here:

https://github.com/Juniper/ansible-junos-stdlib/commit/7bfabf0084d335326a93c967d78be199655397bb

And it was fine.  Just an FYI.  Not sure of what that commit was fixing, but may be worth taking another look or let me know where I'm going wrong on filtering multiple config stanzas :)

**Comment by stacywsmith** [comment]
@jedelman8 

> When I use `filter='interfaces/protocols'` it no longer works.

Were you expecting this to provide you with both the `[edit interfaces]` and `[edit protocols]` top-level configuration hierarchies? I believe that's how it used to work

The problem was that there is no way to specify configuration hierarchies with more than one level. For example, if you wanted just the `[edit system login]` hierarchy.

The intention of the `/` syntax in the value of the `filter` argument was to support the latter, not the former. You should be able to retrieve just the `[edit system login]` hierarchy with  `filter='system/login'` and that's what 7bfabf0 fixes.

Now that I see what you are trying to accomplish, I think this could be supported by allowing the value of the `filter` parameter to be a list. I can work on that enhancement when I return from vacation in a couple of weeks.

**Comment by jedelman8** [comment]
Okay, so maybe I happen to use it in the wrong way initially and it just worked, which is fine.  Totally fine either way though.  As long as I know how it _should_ work :)

**Comment by stacywsmith** [comment]
@jedelman8 I agree it was poorly documented. I also agree that both ways _should_ work. I'll work on the enhancement _and_ improving the documentation. Unfortunately, I won't be able to get to it for a couple of weeks. If you need it sooner feel free to submit your own pull request.

**Comment by vnitinv** [comment]
@jedelman8 I am assuming when things were broken for you, you didn't install Junos roles from galaxy but from github.
If I am correct the changes for this issue is not yet published in galaxy.

**Comment by vnitinv** [comment]
@stacywsmith @jedelman8 I need to release github code to galaxy as there are lot many changes gone in from the last release. Can anyone of you do the changes as per discussed above and send us the pull request?

**Comment by stacywsmith** [comment]
This is now possible with the new `juniper_junos_config` module and a `filter_xml` option specified in XML. Please see my comments on #148 for an example.
