### ISSUE TITLE
junos_install_config randomly firing "list index out of range" error during console access

### ISSUE THREAD

**Issue by renetbo** [Juniper/ansible-junos-stdlib#179]
HI all,
 
When trying to console the devices to push the basic conf, sometimes I’ve got the following error for some boxes:
TASK [fusion_noob_satellites_role : Push temporary satellites config via console] *** 
changed: [EX4300-B1] => {"changed": true} 
changed: [EX4300-A3] => {"changed": true} 
changed: [EX4300-A1] => {"changed": true} 
changed: [EX4300-B3] => {"changed": true} 
fatal: [EX4300-A2]: FAILED! => {"changed": false, "failed": true, "msg": "list index out of range"} 
changed: [EX4300-B2] => {"changed": true}
 
If I run the process again, it might work or not for the same device or another (thus my “random” feeling).
 
The problem is that because it fails, my NOOB process stops there. Moreover, there are other parts l;ater on in the NOOB process where I push config via console so if these last one fail, I need to go through the full process again.

More debugs if needed:
TASK [console_noob_role : Push fusion NOOB config via console] *****************
task path: /usr/local/share/juniper-ansible-noob-roles/console_noob_role/tasks/main.yaml:11
ESTABLISH LOCAL CONNECTION FOR USER: vagrant
EX4300-B3 EXEC /bin/sh -c '( umask 22 && mkdir -p "` echo $HOME/.ansible/tmp/ansible-tmp-1478191648.01-89917446398157 `" && echo "` echo $HOME/.ansible/tmp/ansible-tmp-1478191648.01-89917446398157 `" )'
EX4300-B3 PUT /tmp/tmpZhM611 TO /home/vagrant/.ansible/tmp/ansible-tmp-1478191648.01-89917446398157/junos_install_config
EX4300-B3 EXEC /bin/sh -c 'LANG=en_US.UTF-8 LC_ALL=en_US.UTF-8 LC_MESSAGES=en_US.UTF-8 /usr/bin/env python /home/vagrant/.ansible/tmp/ansible-tmp-1478191648.01-89917446398157/junos_install_config; rm -rf "/home/vagrant/.ansible/tmp/ansible-tmp-1478191648.01-89917446398157/" > /dev/null 2>&1'
fatal: [EX4300-B3]: FAILED! => {"changed": false, "failed": true, "invocation": {"module_args": {"check_commit_wait": null, "comment": null, "confirm": null, "console": "--telnet=172.30.95.138,7027", "diffs_file": null, "file": "/var/tmp/build/EX4300-B3/noob.cfg", "host": "EX4300-B3", "logfile": "/var/tmp/build/EX4300-B3/ansible-run.log", "mode": null, "overwrite": true, "passwd": "Password1", "port": 830, "replace": false, "savedir": null, "timeout": 0, "user": "root"}, "module_name": "junos_install_config"}, "msg": "list index out of range"}

Thanks in advance for your help

Boris

**Comment by gizmoguy** [comment]
I believe this an issue with how netconify parses some junos versions.

They have issue 36 on their github to track this issue: https://github.com/Juniper/py-junos-netconify/issues/36

This is fixed in the as unreleased version 1.0.3 of netconify which you can install via pip/git with:

`sudo pip install --upgrade git+https://github.com/Juniper/py-junos-netconify.git`

**Comment by stacywsmith** [comment]
@renetbo This may have been due to extraneous output being emitted one the device console (WARNING and ERROR-level syslog, ZTP progress, etc.) If that's the case, there's really nothing that can be done by the Ansible module, except to re-execute and try to avoid the extraneous messages.

The `junos_install_config` module has now been re-implemented as `juniper_junos_config` via #290. This continues to support NOOB config installation via telnet to a console server, and now includes better error reporting.

Please re-execute using the new module, and if you're still seeing problems please open a new issue.
