### ISSUE TITLE
how resolv this error PLEASE  fatal: [QFX_17]: FAILED! => {"changed": false, "failed": true, "msg": "unable to connect to XX.XX.XX.XX: ConnectAuthError(XX.XX.XX.XX)"

### ISSUE THREAD

**Issue by mamoudousy** [Juniper/ansible-junos-stdlib#220]
Hey i have a same problem. My error fatal: [QFX_17]: FAILED! => {"changed": false, "failed": true, "msg": "unable to connect to XX.XX.XX.XX: ConnectAuthError(XX.XX.XX.XX)"}

**My inventory**   
QFX_17  ansible_connection=local ansible_ssh_host=XX.XX.XX.XX ansible_ssh_port=830    juniper_user=equiptest   juniper_passwd=****

**my playbook** 

- name: test
    hosts: QFX_17
    connection: local
  
  roles:
  - Juniper.junos
    
  tasks:
  - name: retrieve facts
     junos_facts: 
      host={{ ansible_ssh_host }}  
      user={{ ansible_ssh_user }} 
      passwd={{ juniper_passwd }}
     register: info
  
  - name: affichage
     debug: msg={{ info.facts }}

And i verified my Netconf connection with   ssh equiptest@QFX_17 -p 830 and i get this : 
PTY allocation request failed on channel 0
shell request failed on channel 0

Please can you help me to resolv my error . Thank you

**Comment by stacywsmith** [comment]
You are using the `junos_facts` module which comes from Ansible core rather than the `junos_get_facts` module provided by the `Juniper.junos` role.

You have two options:

1) Change `junos_facts` to `junos_get_facts` in order to use the module from the `Juniper.junos` role.

2) Use the `junos_facts` module from Ansible core correctly by:
   a) Remove `roles: Juniper.junos`
   b) Change `user={{ ansible_ssh_user }}` to `username={{ ansible_ssh_user }}`
   c) Change `passwd={{ juniper_passwd }}` to `password={{ juniper_passwd }}`

**Comment by stacywsmith** [comment]
Incorrectly calling the `junos_facts` Ansible core module.

**Comment by mamoudousy** [comment]
@stacywsmith Thank you for your help. i resolved my error thanks
